{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "26110b4d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe49b2eb",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>place_id</th>\n",
       "      <th>name</th>\n",
       "      <th>rating</th>\n",
       "      <th>reviews_count</th>\n",
       "      <th>lat</th>\n",
       "      <th>lng</th>\n",
       "      <th>types</th>\n",
       "      <th>price_level</th>\n",
       "      <th>query</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>ChIJO-zP-QeIQQ0RypPybBogF2I</td>\n",
       "      <td>Parque de Atracciones de Madrid</td>\n",
       "      <td>4.1</td>\n",
       "      <td>39662.0</td>\n",
       "      <td>40.411883</td>\n",
       "      <td>-3.750058</td>\n",
       "      <td>amusement_park, establishment, point_of_intere...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>ChIJ35PCcoQoQg0RGhxNE3_2Iak</td>\n",
       "      <td>Círculo de Bellas Artes</td>\n",
       "      <td>4.4</td>\n",
       "      <td>33457.0</td>\n",
       "      <td>40.418304</td>\n",
       "      <td>-3.696533</td>\n",
       "      <td>art_gallery, establishment, movie_theater, poi...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>ChIJM7u8_EkmQg0RSH-cbUX_1Yc</td>\n",
       "      <td>Matadero Madrid</td>\n",
       "      <td>4.6</td>\n",
       "      <td>31796.0</td>\n",
       "      <td>40.391945</td>\n",
       "      <td>-3.697883</td>\n",
       "      <td>establishment, museum, point_of_interest, tour...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>ChIJTcV2FZ8oQg0RyFE83TPKXW0</td>\n",
       "      <td>Estanque Grande del Retiro</td>\n",
       "      <td>4.7</td>\n",
       "      <td>34498.0</td>\n",
       "      <td>40.417142</td>\n",
       "      <td>-3.683901</td>\n",
       "      <td>establishment, park, point_of_interest, touris...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>ChIJm1TJPX4oQg0R5uFSWl5x2zU</td>\n",
       "      <td>Clock Tower of Sun Gate</td>\n",
       "      <td>4.7</td>\n",
       "      <td>263.0</td>\n",
       "      <td>40.416558</td>\n",
       "      <td>-3.703785</td>\n",
       "      <td>establishment, point_of_interest, tourist_attr...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1358</th>\n",
       "      <td>ChIJ1f21G5EoQg0RKdq-mKlJf7o</td>\n",
       "      <td>Hotel Fénix Gran Meliá - The Leading Hotels of...</td>\n",
       "      <td>4.6</td>\n",
       "      <td>1774.0</td>\n",
       "      <td>40.426552</td>\n",
       "      <td>-3.689210</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1359</th>\n",
       "      <td>ChIJNQE548AoQg0R-XqEsuRtfKI</td>\n",
       "      <td>Dormirdcine</td>\n",
       "      <td>4.4</td>\n",
       "      <td>1605.0</td>\n",
       "      <td>40.436333</td>\n",
       "      <td>-3.679478</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1360</th>\n",
       "      <td>ChIJ-cFBQccoQg0RjqspaeIpH2I</td>\n",
       "      <td>VP Madroño</td>\n",
       "      <td>4.4</td>\n",
       "      <td>1354.0</td>\n",
       "      <td>40.435131</td>\n",
       "      <td>-3.676565</td>\n",
       "      <td>establishment, food, lodging, point_of_interes...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1361</th>\n",
       "      <td>ChIJb2V2OyQmQg0RFS5Xixm_2RA</td>\n",
       "      <td>Hotel NH Madrid Atocha</td>\n",
       "      <td>4.2</td>\n",
       "      <td>1712.0</td>\n",
       "      <td>40.407690</td>\n",
       "      <td>-3.689457</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Retiro Madrid</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1362</th>\n",
       "      <td>ChIJ28OpiComQg0R9X6BArOIOHg</td>\n",
       "      <td>Hostal Xucar</td>\n",
       "      <td>3.2</td>\n",
       "      <td>107.0</td>\n",
       "      <td>40.412241</td>\n",
       "      <td>-3.700633</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hostels Lavapiés Madrid</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1363 rows × 9 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                         place_id  \\\n",
       "0     ChIJO-zP-QeIQQ0RypPybBogF2I   \n",
       "1     ChIJ35PCcoQoQg0RGhxNE3_2Iak   \n",
       "2     ChIJM7u8_EkmQg0RSH-cbUX_1Yc   \n",
       "3     ChIJTcV2FZ8oQg0RyFE83TPKXW0   \n",
       "4     ChIJm1TJPX4oQg0R5uFSWl5x2zU   \n",
       "...                           ...   \n",
       "1358  ChIJ1f21G5EoQg0RKdq-mKlJf7o   \n",
       "1359  ChIJNQE548AoQg0R-XqEsuRtfKI   \n",
       "1360  ChIJ-cFBQccoQg0RjqspaeIpH2I   \n",
       "1361  ChIJb2V2OyQmQg0RFS5Xixm_2RA   \n",
       "1362  ChIJ28OpiComQg0R9X6BArOIOHg   \n",
       "\n",
       "                                                   name  rating  \\\n",
       "0                       Parque de Atracciones de Madrid     4.1   \n",
       "1                               Círculo de Bellas Artes     4.4   \n",
       "2                                       Matadero Madrid     4.6   \n",
       "3                            Estanque Grande del Retiro     4.7   \n",
       "4                               Clock Tower of Sun Gate     4.7   \n",
       "...                                                 ...     ...   \n",
       "1358  Hotel Fénix Gran Meliá - The Leading Hotels of...     4.6   \n",
       "1359                                        Dormirdcine     4.4   \n",
       "1360                                         VP Madroño     4.4   \n",
       "1361                             Hotel NH Madrid Atocha     4.2   \n",
       "1362                                       Hostal Xucar     3.2   \n",
       "\n",
       "      reviews_count        lat       lng  \\\n",
       "0           39662.0  40.411883 -3.750058   \n",
       "1           33457.0  40.418304 -3.696533   \n",
       "2           31796.0  40.391945 -3.697883   \n",
       "3           34498.0  40.417142 -3.683901   \n",
       "4             263.0  40.416558 -3.703785   \n",
       "...             ...        ...       ...   \n",
       "1358         1774.0  40.426552 -3.689210   \n",
       "1359         1605.0  40.436333 -3.679478   \n",
       "1360         1354.0  40.435131 -3.676565   \n",
       "1361         1712.0  40.407690 -3.689457   \n",
       "1362          107.0  40.412241 -3.700633   \n",
       "\n",
       "                                                  types  price_level  \\\n",
       "0     amusement_park, establishment, point_of_intere...          NaN   \n",
       "1     art_gallery, establishment, movie_theater, poi...          NaN   \n",
       "2     establishment, museum, point_of_interest, tour...          NaN   \n",
       "3     establishment, park, point_of_interest, touris...          NaN   \n",
       "4     establishment, point_of_interest, tourist_attr...          NaN   \n",
       "...                                                 ...          ...   \n",
       "1358          establishment, lodging, point_of_interest          NaN   \n",
       "1359          establishment, lodging, point_of_interest          NaN   \n",
       "1360  establishment, food, lodging, point_of_interes...          NaN   \n",
       "1361          establishment, lodging, point_of_interest          NaN   \n",
       "1362          establishment, lodging, point_of_interest          NaN   \n",
       "\n",
       "                                  query  \n",
       "0     tourist attractions Madrid center  \n",
       "1     tourist attractions Madrid center  \n",
       "2     tourist attractions Madrid center  \n",
       "3     tourist attractions Madrid center  \n",
       "4     tourist attractions Madrid center  \n",
       "...                                 ...  \n",
       "1358            hotels Salamanca Madrid  \n",
       "1359            hotels Salamanca Madrid  \n",
       "1360            hotels Salamanca Madrid  \n",
       "1361               hotels Retiro Madrid  \n",
       "1362            hostels Lavapiés Madrid  \n",
       "\n",
       "[1363 rows x 9 columns]"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# cargar datos\n",
    "df = pd.read_csv(\"madrid_turismo.csv\")\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "262859be",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>place_id</th>\n",
       "      <th>name</th>\n",
       "      <th>rating</th>\n",
       "      <th>reviews_count</th>\n",
       "      <th>lat</th>\n",
       "      <th>lng</th>\n",
       "      <th>types</th>\n",
       "      <th>price_level</th>\n",
       "      <th>query</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>ChIJO-zP-QeIQQ0RypPybBogF2I</td>\n",
       "      <td>Parque de Atracciones de Madrid</td>\n",
       "      <td>4.1</td>\n",
       "      <td>39662.0</td>\n",
       "      <td>40.411883</td>\n",
       "      <td>-3.750058</td>\n",
       "      <td>amusement_park, establishment, point_of_intere...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>ChIJ35PCcoQoQg0RGhxNE3_2Iak</td>\n",
       "      <td>Círculo de Bellas Artes</td>\n",
       "      <td>4.4</td>\n",
       "      <td>33457.0</td>\n",
       "      <td>40.418304</td>\n",
       "      <td>-3.696533</td>\n",
       "      <td>art_gallery, establishment, movie_theater, poi...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>ChIJM7u8_EkmQg0RSH-cbUX_1Yc</td>\n",
       "      <td>Matadero Madrid</td>\n",
       "      <td>4.6</td>\n",
       "      <td>31796.0</td>\n",
       "      <td>40.391945</td>\n",
       "      <td>-3.697883</td>\n",
       "      <td>establishment, museum, point_of_interest, tour...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>ChIJTcV2FZ8oQg0RyFE83TPKXW0</td>\n",
       "      <td>Estanque Grande del Retiro</td>\n",
       "      <td>4.7</td>\n",
       "      <td>34498.0</td>\n",
       "      <td>40.417142</td>\n",
       "      <td>-3.683901</td>\n",
       "      <td>establishment, park, point_of_interest, touris...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>ChIJm1TJPX4oQg0R5uFSWl5x2zU</td>\n",
       "      <td>Clock Tower of Sun Gate</td>\n",
       "      <td>4.7</td>\n",
       "      <td>263.0</td>\n",
       "      <td>40.416558</td>\n",
       "      <td>-3.703785</td>\n",
       "      <td>establishment, point_of_interest, tourist_attr...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1358</th>\n",
       "      <td>ChIJ1f21G5EoQg0RKdq-mKlJf7o</td>\n",
       "      <td>Hotel Fénix Gran Meliá - The Leading Hotels of...</td>\n",
       "      <td>4.6</td>\n",
       "      <td>1774.0</td>\n",
       "      <td>40.426552</td>\n",
       "      <td>-3.689210</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1359</th>\n",
       "      <td>ChIJNQE548AoQg0R-XqEsuRtfKI</td>\n",
       "      <td>Dormirdcine</td>\n",
       "      <td>4.4</td>\n",
       "      <td>1605.0</td>\n",
       "      <td>40.436333</td>\n",
       "      <td>-3.679478</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1360</th>\n",
       "      <td>ChIJ-cFBQccoQg0RjqspaeIpH2I</td>\n",
       "      <td>VP Madroño</td>\n",
       "      <td>4.4</td>\n",
       "      <td>1354.0</td>\n",
       "      <td>40.435131</td>\n",
       "      <td>-3.676565</td>\n",
       "      <td>establishment, food, lodging, point_of_interes...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1361</th>\n",
       "      <td>ChIJb2V2OyQmQg0RFS5Xixm_2RA</td>\n",
       "      <td>Hotel NH Madrid Atocha</td>\n",
       "      <td>4.2</td>\n",
       "      <td>1712.0</td>\n",
       "      <td>40.407690</td>\n",
       "      <td>-3.689457</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Retiro Madrid</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1362</th>\n",
       "      <td>ChIJ28OpiComQg0R9X6BArOIOHg</td>\n",
       "      <td>Hostal Xucar</td>\n",
       "      <td>3.2</td>\n",
       "      <td>107.0</td>\n",
       "      <td>40.412241</td>\n",
       "      <td>-3.700633</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hostels Lavapiés Madrid</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1352 rows × 9 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                         place_id  \\\n",
       "0     ChIJO-zP-QeIQQ0RypPybBogF2I   \n",
       "1     ChIJ35PCcoQoQg0RGhxNE3_2Iak   \n",
       "2     ChIJM7u8_EkmQg0RSH-cbUX_1Yc   \n",
       "3     ChIJTcV2FZ8oQg0RyFE83TPKXW0   \n",
       "4     ChIJm1TJPX4oQg0R5uFSWl5x2zU   \n",
       "...                           ...   \n",
       "1358  ChIJ1f21G5EoQg0RKdq-mKlJf7o   \n",
       "1359  ChIJNQE548AoQg0R-XqEsuRtfKI   \n",
       "1360  ChIJ-cFBQccoQg0RjqspaeIpH2I   \n",
       "1361  ChIJb2V2OyQmQg0RFS5Xixm_2RA   \n",
       "1362  ChIJ28OpiComQg0R9X6BArOIOHg   \n",
       "\n",
       "                                                   name  rating  \\\n",
       "0                       Parque de Atracciones de Madrid     4.1   \n",
       "1                               Círculo de Bellas Artes     4.4   \n",
       "2                                       Matadero Madrid     4.6   \n",
       "3                            Estanque Grande del Retiro     4.7   \n",
       "4                               Clock Tower of Sun Gate     4.7   \n",
       "...                                                 ...     ...   \n",
       "1358  Hotel Fénix Gran Meliá - The Leading Hotels of...     4.6   \n",
       "1359                                        Dormirdcine     4.4   \n",
       "1360                                         VP Madroño     4.4   \n",
       "1361                             Hotel NH Madrid Atocha     4.2   \n",
       "1362                                       Hostal Xucar     3.2   \n",
       "\n",
       "      reviews_count        lat       lng  \\\n",
       "0           39662.0  40.411883 -3.750058   \n",
       "1           33457.0  40.418304 -3.696533   \n",
       "2           31796.0  40.391945 -3.697883   \n",
       "3           34498.0  40.417142 -3.683901   \n",
       "4             263.0  40.416558 -3.703785   \n",
       "...             ...        ...       ...   \n",
       "1358         1774.0  40.426552 -3.689210   \n",
       "1359         1605.0  40.436333 -3.679478   \n",
       "1360         1354.0  40.435131 -3.676565   \n",
       "1361         1712.0  40.407690 -3.689457   \n",
       "1362          107.0  40.412241 -3.700633   \n",
       "\n",
       "                                                  types  price_level  \\\n",
       "0     amusement_park, establishment, point_of_intere...          NaN   \n",
       "1     art_gallery, establishment, movie_theater, poi...          NaN   \n",
       "2     establishment, museum, point_of_interest, tour...          NaN   \n",
       "3     establishment, park, point_of_interest, touris...          NaN   \n",
       "4     establishment, point_of_interest, tourist_attr...          NaN   \n",
       "...                                                 ...          ...   \n",
       "1358          establishment, lodging, point_of_interest          NaN   \n",
       "1359          establishment, lodging, point_of_interest          NaN   \n",
       "1360  establishment, food, lodging, point_of_interes...          NaN   \n",
       "1361          establishment, lodging, point_of_interest          NaN   \n",
       "1362          establishment, lodging, point_of_interest          NaN   \n",
       "\n",
       "                                  query  \n",
       "0     tourist attractions Madrid center  \n",
       "1     tourist attractions Madrid center  \n",
       "2     tourist attractions Madrid center  \n",
       "3     tourist attractions Madrid center  \n",
       "4     tourist attractions Madrid center  \n",
       "...                                 ...  \n",
       "1358            hotels Salamanca Madrid  \n",
       "1359            hotels Salamanca Madrid  \n",
       "1360            hotels Salamanca Madrid  \n",
       "1361               hotels Retiro Madrid  \n",
       "1362            hostels Lavapiés Madrid  \n",
       "\n",
       "[1352 rows x 9 columns]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# limpiar datos fuera de madrid con filtros de latitud y longitud\n",
    "df = df[\n",
    "    (df[\"lat\"] >= 40.30) & (df[\"lat\"] <= 40.55) &\n",
    "    (df[\"lng\"] >= -3.80) & (df[\"lng\"] <= -3.55)\n",
    "]\n",
    "\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aae40256",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\marta\\AppData\\Local\\Temp\\ipykernel_11964\\355362136.py:19: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[\"Zona\"] = df[\"query\"].apply(extraer_zona)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>place_id</th>\n",
       "      <th>name</th>\n",
       "      <th>rating</th>\n",
       "      <th>reviews_count</th>\n",
       "      <th>lat</th>\n",
       "      <th>lng</th>\n",
       "      <th>types</th>\n",
       "      <th>price_level</th>\n",
       "      <th>query</th>\n",
       "      <th>Zona</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>ChIJO-zP-QeIQQ0RypPybBogF2I</td>\n",
       "      <td>Parque de Atracciones de Madrid</td>\n",
       "      <td>4.1</td>\n",
       "      <td>39662.0</td>\n",
       "      <td>40.411883</td>\n",
       "      <td>-3.750058</td>\n",
       "      <td>amusement_park, establishment, point_of_intere...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>ChIJ35PCcoQoQg0RGhxNE3_2Iak</td>\n",
       "      <td>Círculo de Bellas Artes</td>\n",
       "      <td>4.4</td>\n",
       "      <td>33457.0</td>\n",
       "      <td>40.418304</td>\n",
       "      <td>-3.696533</td>\n",
       "      <td>art_gallery, establishment, movie_theater, poi...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>ChIJM7u8_EkmQg0RSH-cbUX_1Yc</td>\n",
       "      <td>Matadero Madrid</td>\n",
       "      <td>4.6</td>\n",
       "      <td>31796.0</td>\n",
       "      <td>40.391945</td>\n",
       "      <td>-3.697883</td>\n",
       "      <td>establishment, museum, point_of_interest, tour...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>ChIJTcV2FZ8oQg0RyFE83TPKXW0</td>\n",
       "      <td>Estanque Grande del Retiro</td>\n",
       "      <td>4.7</td>\n",
       "      <td>34498.0</td>\n",
       "      <td>40.417142</td>\n",
       "      <td>-3.683901</td>\n",
       "      <td>establishment, park, point_of_interest, touris...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>ChIJm1TJPX4oQg0R5uFSWl5x2zU</td>\n",
       "      <td>Clock Tower of Sun Gate</td>\n",
       "      <td>4.7</td>\n",
       "      <td>263.0</td>\n",
       "      <td>40.416558</td>\n",
       "      <td>-3.703785</td>\n",
       "      <td>establishment, point_of_interest, tourist_attr...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1358</th>\n",
       "      <td>ChIJ1f21G5EoQg0RKdq-mKlJf7o</td>\n",
       "      <td>Hotel Fénix Gran Meliá - The Leading Hotels of...</td>\n",
       "      <td>4.6</td>\n",
       "      <td>1774.0</td>\n",
       "      <td>40.426552</td>\n",
       "      <td>-3.689210</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "      <td>Salamanca</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1359</th>\n",
       "      <td>ChIJNQE548AoQg0R-XqEsuRtfKI</td>\n",
       "      <td>Dormirdcine</td>\n",
       "      <td>4.4</td>\n",
       "      <td>1605.0</td>\n",
       "      <td>40.436333</td>\n",
       "      <td>-3.679478</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "      <td>Salamanca</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1360</th>\n",
       "      <td>ChIJ-cFBQccoQg0RjqspaeIpH2I</td>\n",
       "      <td>VP Madroño</td>\n",
       "      <td>4.4</td>\n",
       "      <td>1354.0</td>\n",
       "      <td>40.435131</td>\n",
       "      <td>-3.676565</td>\n",
       "      <td>establishment, food, lodging, point_of_interes...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "      <td>Salamanca</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1361</th>\n",
       "      <td>ChIJb2V2OyQmQg0RFS5Xixm_2RA</td>\n",
       "      <td>Hotel NH Madrid Atocha</td>\n",
       "      <td>4.2</td>\n",
       "      <td>1712.0</td>\n",
       "      <td>40.407690</td>\n",
       "      <td>-3.689457</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Retiro Madrid</td>\n",
       "      <td>Retiro</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1362</th>\n",
       "      <td>ChIJ28OpiComQg0R9X6BArOIOHg</td>\n",
       "      <td>Hostal Xucar</td>\n",
       "      <td>3.2</td>\n",
       "      <td>107.0</td>\n",
       "      <td>40.412241</td>\n",
       "      <td>-3.700633</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hostels Lavapiés Madrid</td>\n",
       "      <td>Lavapiés</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1352 rows × 10 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                         place_id  \\\n",
       "0     ChIJO-zP-QeIQQ0RypPybBogF2I   \n",
       "1     ChIJ35PCcoQoQg0RGhxNE3_2Iak   \n",
       "2     ChIJM7u8_EkmQg0RSH-cbUX_1Yc   \n",
       "3     ChIJTcV2FZ8oQg0RyFE83TPKXW0   \n",
       "4     ChIJm1TJPX4oQg0R5uFSWl5x2zU   \n",
       "...                           ...   \n",
       "1358  ChIJ1f21G5EoQg0RKdq-mKlJf7o   \n",
       "1359  ChIJNQE548AoQg0R-XqEsuRtfKI   \n",
       "1360  ChIJ-cFBQccoQg0RjqspaeIpH2I   \n",
       "1361  ChIJb2V2OyQmQg0RFS5Xixm_2RA   \n",
       "1362  ChIJ28OpiComQg0R9X6BArOIOHg   \n",
       "\n",
       "                                                   name  rating  \\\n",
       "0                       Parque de Atracciones de Madrid     4.1   \n",
       "1                               Círculo de Bellas Artes     4.4   \n",
       "2                                       Matadero Madrid     4.6   \n",
       "3                            Estanque Grande del Retiro     4.7   \n",
       "4                               Clock Tower of Sun Gate     4.7   \n",
       "...                                                 ...     ...   \n",
       "1358  Hotel Fénix Gran Meliá - The Leading Hotels of...     4.6   \n",
       "1359                                        Dormirdcine     4.4   \n",
       "1360                                         VP Madroño     4.4   \n",
       "1361                             Hotel NH Madrid Atocha     4.2   \n",
       "1362                                       Hostal Xucar     3.2   \n",
       "\n",
       "      reviews_count        lat       lng  \\\n",
       "0           39662.0  40.411883 -3.750058   \n",
       "1           33457.0  40.418304 -3.696533   \n",
       "2           31796.0  40.391945 -3.697883   \n",
       "3           34498.0  40.417142 -3.683901   \n",
       "4             263.0  40.416558 -3.703785   \n",
       "...             ...        ...       ...   \n",
       "1358         1774.0  40.426552 -3.689210   \n",
       "1359         1605.0  40.436333 -3.679478   \n",
       "1360         1354.0  40.435131 -3.676565   \n",
       "1361         1712.0  40.407690 -3.689457   \n",
       "1362          107.0  40.412241 -3.700633   \n",
       "\n",
       "                                                  types  price_level  \\\n",
       "0     amusement_park, establishment, point_of_intere...          NaN   \n",
       "1     art_gallery, establishment, movie_theater, poi...          NaN   \n",
       "2     establishment, museum, point_of_interest, tour...          NaN   \n",
       "3     establishment, park, point_of_interest, touris...          NaN   \n",
       "4     establishment, point_of_interest, tourist_attr...          NaN   \n",
       "...                                                 ...          ...   \n",
       "1358          establishment, lodging, point_of_interest          NaN   \n",
       "1359          establishment, lodging, point_of_interest          NaN   \n",
       "1360  establishment, food, lodging, point_of_interes...          NaN   \n",
       "1361          establishment, lodging, point_of_interest          NaN   \n",
       "1362          establishment, lodging, point_of_interest          NaN   \n",
       "\n",
       "                                  query       Zona  \n",
       "0     tourist attractions Madrid center     Centro  \n",
       "1     tourist attractions Madrid center     Centro  \n",
       "2     tourist attractions Madrid center     Centro  \n",
       "3     tourist attractions Madrid center     Centro  \n",
       "4     tourist attractions Madrid center     Centro  \n",
       "...                                 ...        ...  \n",
       "1358            hotels Salamanca Madrid  Salamanca  \n",
       "1359            hotels Salamanca Madrid  Salamanca  \n",
       "1360            hotels Salamanca Madrid  Salamanca  \n",
       "1361               hotels Retiro Madrid     Retiro  \n",
       "1362            hostels Lavapiés Madrid   Lavapiés  \n",
       "\n",
       "[1352 rows x 10 columns]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# añadir categoría zona a partir de las queries\n",
    "zonas_dict = {\n",
    "    \"malasaña\": \"Malasaña\",\n",
    "    \"chueca\": \"Chueca\",\n",
    "    \"salamanca\": \"Salamanca\",\n",
    "    \"lavapiés\": \"Lavapiés\",\n",
    "    \"la latina\": \"La Latina\",\n",
    "    \"chamartín\": \"Chamartín\",\n",
    "    \"retiro\": \"Retiro\",\n",
    "    \"center\": \"Centro\"\n",
    "}\n",
    "\n",
    "def extraer_zona(query):\n",
    "    q = str(query).lower()\n",
    "    for key, value in zonas_dict.items():\n",
    "        if key in q:\n",
    "            return value\n",
    "    return \"Otros\"\n",
    "\n",
    "df[\"Zona\"] = df[\"query\"].apply(extraer_zona)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6fe5116c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\marta\\AppData\\Local\\Temp\\ipykernel_11964\\2479620035.py:34: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[\"Categoria_general\"] = df[\"query\"].apply(extraer_categoria)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>place_id</th>\n",
       "      <th>name</th>\n",
       "      <th>rating</th>\n",
       "      <th>reviews_count</th>\n",
       "      <th>lat</th>\n",
       "      <th>lng</th>\n",
       "      <th>types</th>\n",
       "      <th>price_level</th>\n",
       "      <th>query</th>\n",
       "      <th>Zona</th>\n",
       "      <th>Categoria_general</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>ChIJO-zP-QeIQQ0RypPybBogF2I</td>\n",
       "      <td>Parque de Atracciones de Madrid</td>\n",
       "      <td>4.1</td>\n",
       "      <td>39662.0</td>\n",
       "      <td>40.411883</td>\n",
       "      <td>-3.750058</td>\n",
       "      <td>amusement_park, establishment, point_of_intere...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "      <td>Cultura</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>ChIJ35PCcoQoQg0RGhxNE3_2Iak</td>\n",
       "      <td>Círculo de Bellas Artes</td>\n",
       "      <td>4.4</td>\n",
       "      <td>33457.0</td>\n",
       "      <td>40.418304</td>\n",
       "      <td>-3.696533</td>\n",
       "      <td>art_gallery, establishment, movie_theater, poi...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "      <td>Cultura</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>ChIJM7u8_EkmQg0RSH-cbUX_1Yc</td>\n",
       "      <td>Matadero Madrid</td>\n",
       "      <td>4.6</td>\n",
       "      <td>31796.0</td>\n",
       "      <td>40.391945</td>\n",
       "      <td>-3.697883</td>\n",
       "      <td>establishment, museum, point_of_interest, tour...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "      <td>Cultura</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>ChIJTcV2FZ8oQg0RyFE83TPKXW0</td>\n",
       "      <td>Estanque Grande del Retiro</td>\n",
       "      <td>4.7</td>\n",
       "      <td>34498.0</td>\n",
       "      <td>40.417142</td>\n",
       "      <td>-3.683901</td>\n",
       "      <td>establishment, park, point_of_interest, touris...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "      <td>Cultura</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>ChIJm1TJPX4oQg0R5uFSWl5x2zU</td>\n",
       "      <td>Clock Tower of Sun Gate</td>\n",
       "      <td>4.7</td>\n",
       "      <td>263.0</td>\n",
       "      <td>40.416558</td>\n",
       "      <td>-3.703785</td>\n",
       "      <td>establishment, point_of_interest, tourist_attr...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "      <td>Cultura</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1358</th>\n",
       "      <td>ChIJ1f21G5EoQg0RKdq-mKlJf7o</td>\n",
       "      <td>Hotel Fénix Gran Meliá - The Leading Hotels of...</td>\n",
       "      <td>4.6</td>\n",
       "      <td>1774.0</td>\n",
       "      <td>40.426552</td>\n",
       "      <td>-3.689210</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "      <td>Salamanca</td>\n",
       "      <td>Alojamiento</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1359</th>\n",
       "      <td>ChIJNQE548AoQg0R-XqEsuRtfKI</td>\n",
       "      <td>Dormirdcine</td>\n",
       "      <td>4.4</td>\n",
       "      <td>1605.0</td>\n",
       "      <td>40.436333</td>\n",
       "      <td>-3.679478</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "      <td>Salamanca</td>\n",
       "      <td>Alojamiento</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1360</th>\n",
       "      <td>ChIJ-cFBQccoQg0RjqspaeIpH2I</td>\n",
       "      <td>VP Madroño</td>\n",
       "      <td>4.4</td>\n",
       "      <td>1354.0</td>\n",
       "      <td>40.435131</td>\n",
       "      <td>-3.676565</td>\n",
       "      <td>establishment, food, lodging, point_of_interes...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "      <td>Salamanca</td>\n",
       "      <td>Alojamiento</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1361</th>\n",
       "      <td>ChIJb2V2OyQmQg0RFS5Xixm_2RA</td>\n",
       "      <td>Hotel NH Madrid Atocha</td>\n",
       "      <td>4.2</td>\n",
       "      <td>1712.0</td>\n",
       "      <td>40.407690</td>\n",
       "      <td>-3.689457</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Retiro Madrid</td>\n",
       "      <td>Retiro</td>\n",
       "      <td>Alojamiento</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1362</th>\n",
       "      <td>ChIJ28OpiComQg0R9X6BArOIOHg</td>\n",
       "      <td>Hostal Xucar</td>\n",
       "      <td>3.2</td>\n",
       "      <td>107.0</td>\n",
       "      <td>40.412241</td>\n",
       "      <td>-3.700633</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hostels Lavapiés Madrid</td>\n",
       "      <td>Lavapiés</td>\n",
       "      <td>Alojamiento</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1352 rows × 11 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                         place_id  \\\n",
       "0     ChIJO-zP-QeIQQ0RypPybBogF2I   \n",
       "1     ChIJ35PCcoQoQg0RGhxNE3_2Iak   \n",
       "2     ChIJM7u8_EkmQg0RSH-cbUX_1Yc   \n",
       "3     ChIJTcV2FZ8oQg0RyFE83TPKXW0   \n",
       "4     ChIJm1TJPX4oQg0R5uFSWl5x2zU   \n",
       "...                           ...   \n",
       "1358  ChIJ1f21G5EoQg0RKdq-mKlJf7o   \n",
       "1359  ChIJNQE548AoQg0R-XqEsuRtfKI   \n",
       "1360  ChIJ-cFBQccoQg0RjqspaeIpH2I   \n",
       "1361  ChIJb2V2OyQmQg0RFS5Xixm_2RA   \n",
       "1362  ChIJ28OpiComQg0R9X6BArOIOHg   \n",
       "\n",
       "                                                   name  rating  \\\n",
       "0                       Parque de Atracciones de Madrid     4.1   \n",
       "1                               Círculo de Bellas Artes     4.4   \n",
       "2                                       Matadero Madrid     4.6   \n",
       "3                            Estanque Grande del Retiro     4.7   \n",
       "4                               Clock Tower of Sun Gate     4.7   \n",
       "...                                                 ...     ...   \n",
       "1358  Hotel Fénix Gran Meliá - The Leading Hotels of...     4.6   \n",
       "1359                                        Dormirdcine     4.4   \n",
       "1360                                         VP Madroño     4.4   \n",
       "1361                             Hotel NH Madrid Atocha     4.2   \n",
       "1362                                       Hostal Xucar     3.2   \n",
       "\n",
       "      reviews_count        lat       lng  \\\n",
       "0           39662.0  40.411883 -3.750058   \n",
       "1           33457.0  40.418304 -3.696533   \n",
       "2           31796.0  40.391945 -3.697883   \n",
       "3           34498.0  40.417142 -3.683901   \n",
       "4             263.0  40.416558 -3.703785   \n",
       "...             ...        ...       ...   \n",
       "1358         1774.0  40.426552 -3.689210   \n",
       "1359         1605.0  40.436333 -3.679478   \n",
       "1360         1354.0  40.435131 -3.676565   \n",
       "1361         1712.0  40.407690 -3.689457   \n",
       "1362          107.0  40.412241 -3.700633   \n",
       "\n",
       "                                                  types  price_level  \\\n",
       "0     amusement_park, establishment, point_of_intere...          NaN   \n",
       "1     art_gallery, establishment, movie_theater, poi...          NaN   \n",
       "2     establishment, museum, point_of_interest, tour...          NaN   \n",
       "3     establishment, park, point_of_interest, touris...          NaN   \n",
       "4     establishment, point_of_interest, tourist_attr...          NaN   \n",
       "...                                                 ...          ...   \n",
       "1358          establishment, lodging, point_of_interest          NaN   \n",
       "1359          establishment, lodging, point_of_interest          NaN   \n",
       "1360  establishment, food, lodging, point_of_interes...          NaN   \n",
       "1361          establishment, lodging, point_of_interest          NaN   \n",
       "1362          establishment, lodging, point_of_interest          NaN   \n",
       "\n",
       "                                  query       Zona Categoria_general  \n",
       "0     tourist attractions Madrid center     Centro           Cultura  \n",
       "1     tourist attractions Madrid center     Centro           Cultura  \n",
       "2     tourist attractions Madrid center     Centro           Cultura  \n",
       "3     tourist attractions Madrid center     Centro           Cultura  \n",
       "4     tourist attractions Madrid center     Centro           Cultura  \n",
       "...                                 ...        ...               ...  \n",
       "1358            hotels Salamanca Madrid  Salamanca       Alojamiento  \n",
       "1359            hotels Salamanca Madrid  Salamanca       Alojamiento  \n",
       "1360            hotels Salamanca Madrid  Salamanca       Alojamiento  \n",
       "1361               hotels Retiro Madrid     Retiro       Alojamiento  \n",
       "1362            hostels Lavapiés Madrid   Lavapiés       Alojamiento  \n",
       "\n",
       "[1352 rows x 11 columns]"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# añadir categoría turística a partir de las queries\n",
    "categorias_dict = {\n",
    "    \"Cultura\": [\n",
    "        \"museum\", \"museums\",\n",
    "        \"art museum\",\n",
    "        \"tourist\", \"tourist attraction\",\n",
    "        \"things to do\"\n",
    "    ],\n",
    "    \n",
    "    \"Food & Drink\": [\n",
    "        \"restaurant\", \"restaurants\",\n",
    "        \"tapas\",\n",
    "        \"bar\", \"bars\",\n",
    "        \"cocktail\",\n",
    "        \"cafe\", \"cafes\",\n",
    "        \"brunch\"\n",
    "    ],\n",
    "    \n",
    "    \"Alojamiento\": [\n",
    "        \"hotel\", \"hotels\",\n",
    "        \"hostel\", \"hostels\",\n",
    "        \"lodging\"\n",
    "    ]\n",
    "}\n",
    "\n",
    "def extraer_categoria(query):\n",
    "    q = str(query).lower()\n",
    "    \n",
    "    for categoria, keywords in categorias_dict.items():\n",
    "        if any(keyword in q for keyword in keywords):\n",
    "            return categoria\n",
    "    \n",
    "    return \"Otros\"\n",
    "\n",
    "df[\"Categoria_general\"] = df[\"query\"].apply(extraer_categoria)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "20fca286",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\marta\\AppData\\Local\\Temp\\ipykernel_11964\\2124729893.py:2: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[\"Score_popularidad\"] = df[\"rating\"] * np.log1p(df[\"reviews_count\"])\n",
      "C:\\Users\\marta\\AppData\\Local\\Temp\\ipykernel_11964\\2124729893.py:7: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[\"Score_popularidad_clip\"] = df[\"Score_popularidad\"].clip(p1, p99)\n",
      "C:\\Users\\marta\\AppData\\Local\\Temp\\ipykernel_11964\\2124729893.py:9: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[\"Score_popularidad_norm\"] = 1 + 9 * (\n"
     ]
    }
   ],
   "source": [
    "# Añadir score de popularidad\n",
    "df[\"Score_popularidad\"] = df[\"rating\"] * np.log1p(df[\"reviews_count\"])\n",
    "\n",
    "p1 = df[\"Score_popularidad\"].quantile(0.01)\n",
    "p99 = df[\"Score_popularidad\"].quantile(0.99)\n",
    "\n",
    "df[\"Score_popularidad_clip\"] = df[\"Score_popularidad\"].clip(p1, p99)\n",
    "\n",
    "df[\"Score_popularidad_norm\"] = 1 + 9 * (\n",
    "    (df[\"Score_popularidad_clip\"] - p1) / (p99 - p1)\n",
    ")\n",
    "\n",
    "df = df.drop(columns=[\"Score_popularidad_clip\"], axis=1)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9c170bb2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>place_id</th>\n",
       "      <th>name</th>\n",
       "      <th>rating</th>\n",
       "      <th>reviews_count</th>\n",
       "      <th>lat</th>\n",
       "      <th>lng</th>\n",
       "      <th>types</th>\n",
       "      <th>price_level</th>\n",
       "      <th>query</th>\n",
       "      <th>Zona</th>\n",
       "      <th>Categoria_general</th>\n",
       "      <th>Score_popularidad</th>\n",
       "      <th>Score_popularidad_norm</th>\n",
       "      <th>Densidad</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>ChIJO-zP-QeIQQ0RypPybBogF2I</td>\n",
       "      <td>Parque de Atracciones de Madrid</td>\n",
       "      <td>4.1</td>\n",
       "      <td>39662.0</td>\n",
       "      <td>40.411883</td>\n",
       "      <td>-3.750058</td>\n",
       "      <td>amusement_park, establishment, point_of_intere...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "      <td>Cultura</td>\n",
       "      <td>43.411514</td>\n",
       "      <td>8.949629</td>\n",
       "      <td>212</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>ChIJ35PCcoQoQg0RGhxNE3_2Iak</td>\n",
       "      <td>Círculo de Bellas Artes</td>\n",
       "      <td>4.4</td>\n",
       "      <td>33457.0</td>\n",
       "      <td>40.418304</td>\n",
       "      <td>-3.696533</td>\n",
       "      <td>art_gallery, establishment, movie_theater, poi...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "      <td>Cultura</td>\n",
       "      <td>45.839403</td>\n",
       "      <td>9.451370</td>\n",
       "      <td>212</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>ChIJM7u8_EkmQg0RSH-cbUX_1Yc</td>\n",
       "      <td>Matadero Madrid</td>\n",
       "      <td>4.6</td>\n",
       "      <td>31796.0</td>\n",
       "      <td>40.391945</td>\n",
       "      <td>-3.697883</td>\n",
       "      <td>establishment, museum, point_of_interest, tour...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "      <td>Cultura</td>\n",
       "      <td>47.688785</td>\n",
       "      <td>9.833557</td>\n",
       "      <td>212</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>ChIJTcV2FZ8oQg0RyFE83TPKXW0</td>\n",
       "      <td>Estanque Grande del Retiro</td>\n",
       "      <td>4.7</td>\n",
       "      <td>34498.0</td>\n",
       "      <td>40.417142</td>\n",
       "      <td>-3.683901</td>\n",
       "      <td>establishment, park, point_of_interest, touris...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "      <td>Cultura</td>\n",
       "      <td>49.108822</td>\n",
       "      <td>10.000000</td>\n",
       "      <td>212</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>ChIJm1TJPX4oQg0R5uFSWl5x2zU</td>\n",
       "      <td>Clock Tower of Sun Gate</td>\n",
       "      <td>4.7</td>\n",
       "      <td>263.0</td>\n",
       "      <td>40.416558</td>\n",
       "      <td>-3.703785</td>\n",
       "      <td>establishment, point_of_interest, tourist_attr...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>tourist attractions Madrid center</td>\n",
       "      <td>Centro</td>\n",
       "      <td>Cultura</td>\n",
       "      <td>26.206961</td>\n",
       "      <td>5.394189</td>\n",
       "      <td>212</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1358</th>\n",
       "      <td>ChIJ1f21G5EoQg0RKdq-mKlJf7o</td>\n",
       "      <td>Hotel Fénix Gran Meliá - The Leading Hotels of...</td>\n",
       "      <td>4.6</td>\n",
       "      <td>1774.0</td>\n",
       "      <td>40.426552</td>\n",
       "      <td>-3.689210</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "      <td>Salamanca</td>\n",
       "      <td>Alojamiento</td>\n",
       "      <td>34.415156</td>\n",
       "      <td>7.090470</td>\n",
       "      <td>167</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1359</th>\n",
       "      <td>ChIJNQE548AoQg0R-XqEsuRtfKI</td>\n",
       "      <td>Dormirdcine</td>\n",
       "      <td>4.4</td>\n",
       "      <td>1605.0</td>\n",
       "      <td>40.436333</td>\n",
       "      <td>-3.679478</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "      <td>Salamanca</td>\n",
       "      <td>Alojamiento</td>\n",
       "      <td>32.478608</td>\n",
       "      <td>6.690269</td>\n",
       "      <td>167</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1360</th>\n",
       "      <td>ChIJ-cFBQccoQg0RjqspaeIpH2I</td>\n",
       "      <td>VP Madroño</td>\n",
       "      <td>4.4</td>\n",
       "      <td>1354.0</td>\n",
       "      <td>40.435131</td>\n",
       "      <td>-3.676565</td>\n",
       "      <td>establishment, food, lodging, point_of_interes...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Salamanca Madrid</td>\n",
       "      <td>Salamanca</td>\n",
       "      <td>Alojamiento</td>\n",
       "      <td>31.730850</td>\n",
       "      <td>6.535739</td>\n",
       "      <td>167</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1361</th>\n",
       "      <td>ChIJb2V2OyQmQg0RFS5Xixm_2RA</td>\n",
       "      <td>Hotel NH Madrid Atocha</td>\n",
       "      <td>4.2</td>\n",
       "      <td>1712.0</td>\n",
       "      <td>40.407690</td>\n",
       "      <td>-3.689457</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hotels Retiro Madrid</td>\n",
       "      <td>Retiro</td>\n",
       "      <td>Alojamiento</td>\n",
       "      <td>31.273206</td>\n",
       "      <td>6.441164</td>\n",
       "      <td>143</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1362</th>\n",
       "      <td>ChIJ28OpiComQg0R9X6BArOIOHg</td>\n",
       "      <td>Hostal Xucar</td>\n",
       "      <td>3.2</td>\n",
       "      <td>107.0</td>\n",
       "      <td>40.412241</td>\n",
       "      <td>-3.700633</td>\n",
       "      <td>establishment, lodging, point_of_interest</td>\n",
       "      <td>NaN</td>\n",
       "      <td>hostels Lavapiés Madrid</td>\n",
       "      <td>Lavapiés</td>\n",
       "      <td>Alojamiento</td>\n",
       "      <td>14.982820</td>\n",
       "      <td>3.074642</td>\n",
       "      <td>161</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1352 rows × 14 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                         place_id  \\\n",
       "0     ChIJO-zP-QeIQQ0RypPybBogF2I   \n",
       "1     ChIJ35PCcoQoQg0RGhxNE3_2Iak   \n",
       "2     ChIJM7u8_EkmQg0RSH-cbUX_1Yc   \n",
       "3     ChIJTcV2FZ8oQg0RyFE83TPKXW0   \n",
       "4     ChIJm1TJPX4oQg0R5uFSWl5x2zU   \n",
       "...                           ...   \n",
       "1358  ChIJ1f21G5EoQg0RKdq-mKlJf7o   \n",
       "1359  ChIJNQE548AoQg0R-XqEsuRtfKI   \n",
       "1360  ChIJ-cFBQccoQg0RjqspaeIpH2I   \n",
       "1361  ChIJb2V2OyQmQg0RFS5Xixm_2RA   \n",
       "1362  ChIJ28OpiComQg0R9X6BArOIOHg   \n",
       "\n",
       "                                                   name  rating  \\\n",
       "0                       Parque de Atracciones de Madrid     4.1   \n",
       "1                               Círculo de Bellas Artes     4.4   \n",
       "2                                       Matadero Madrid     4.6   \n",
       "3                            Estanque Grande del Retiro     4.7   \n",
       "4                               Clock Tower of Sun Gate     4.7   \n",
       "...                                                 ...     ...   \n",
       "1358  Hotel Fénix Gran Meliá - The Leading Hotels of...     4.6   \n",
       "1359                                        Dormirdcine     4.4   \n",
       "1360                                         VP Madroño     4.4   \n",
       "1361                             Hotel NH Madrid Atocha     4.2   \n",
       "1362                                       Hostal Xucar     3.2   \n",
       "\n",
       "      reviews_count        lat       lng  \\\n",
       "0           39662.0  40.411883 -3.750058   \n",
       "1           33457.0  40.418304 -3.696533   \n",
       "2           31796.0  40.391945 -3.697883   \n",
       "3           34498.0  40.417142 -3.683901   \n",
       "4             263.0  40.416558 -3.703785   \n",
       "...             ...        ...       ...   \n",
       "1358         1774.0  40.426552 -3.689210   \n",
       "1359         1605.0  40.436333 -3.679478   \n",
       "1360         1354.0  40.435131 -3.676565   \n",
       "1361         1712.0  40.407690 -3.689457   \n",
       "1362          107.0  40.412241 -3.700633   \n",
       "\n",
       "                                                  types  price_level  \\\n",
       "0     amusement_park, establishment, point_of_intere...          NaN   \n",
       "1     art_gallery, establishment, movie_theater, poi...          NaN   \n",
       "2     establishment, museum, point_of_interest, tour...          NaN   \n",
       "3     establishment, park, point_of_interest, touris...          NaN   \n",
       "4     establishment, point_of_interest, tourist_attr...          NaN   \n",
       "...                                                 ...          ...   \n",
       "1358          establishment, lodging, point_of_interest          NaN   \n",
       "1359          establishment, lodging, point_of_interest          NaN   \n",
       "1360  establishment, food, lodging, point_of_interes...          NaN   \n",
       "1361          establishment, lodging, point_of_interest          NaN   \n",
       "1362          establishment, lodging, point_of_interest          NaN   \n",
       "\n",
       "                                  query       Zona Categoria_general  \\\n",
       "0     tourist attractions Madrid center     Centro           Cultura   \n",
       "1     tourist attractions Madrid center     Centro           Cultura   \n",
       "2     tourist attractions Madrid center     Centro           Cultura   \n",
       "3     tourist attractions Madrid center     Centro           Cultura   \n",
       "4     tourist attractions Madrid center     Centro           Cultura   \n",
       "...                                 ...        ...               ...   \n",
       "1358            hotels Salamanca Madrid  Salamanca       Alojamiento   \n",
       "1359            hotels Salamanca Madrid  Salamanca       Alojamiento   \n",
       "1360            hotels Salamanca Madrid  Salamanca       Alojamiento   \n",
       "1361               hotels Retiro Madrid     Retiro       Alojamiento   \n",
       "1362            hostels Lavapiés Madrid   Lavapiés       Alojamiento   \n",
       "\n",
       "      Score_popularidad  Score_popularidad_norm  Densidad  \n",
       "0             43.411514                8.949629       212  \n",
       "1             45.839403                9.451370       212  \n",
       "2             47.688785                9.833557       212  \n",
       "3             49.108822               10.000000       212  \n",
       "4             26.206961                5.394189       212  \n",
       "...                 ...                     ...       ...  \n",
       "1358          34.415156                7.090470       167  \n",
       "1359          32.478608                6.690269       167  \n",
       "1360          31.730850                6.535739       167  \n",
       "1361          31.273206                6.441164       143  \n",
       "1362          14.982820                3.074642       161  \n",
       "\n",
       "[1352 rows x 14 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# cálculo de densidad por zona\n",
    "df[\"Densidad\"] = df.groupby(\"Zona\")[\"place_id\"].transform(\"count\")\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "29c65149",
   "metadata": {},
   "outputs": [],
   "source": [
    "# guardar dataset\n",
    "df.to_csv(\"madrid_turismo_enriched.csv\", index=False, sep=\";\", decimal=\",\", encoding=\"utf-8\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Lab_IA_01",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.25"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
